Debugger.exe -v ../../../Tests/Byte/afetch.bpsc
Debugger.exe -v ../../../Tests/Byte/and.bpsc
Debugger.exe -v ../../../Tests/Byte/apop.bpsc
Debugger.exe -v ../../../Tests/Byte/apush.bpsc
Debugger.exe -v ../../../Tests/Byte/array.bpsc
Debugger.exe -v ../../../Tests/Byte/astore.bpsc
Debugger.exe -v ../../../Tests/Byte/call.bpsc
Debugger.exe -v ../../../Tests/Byte/concat.bpsc
Debugger.exe -v ../../../Tests/Byte/derase.bpsc
Debugger.exe -v ../../../Tests/Byte/dfetch.bpsc
Debugger.exe -v ../../../Tests/Byte/dinsert.bpsc
Debugger.exe -v ../../../Tests/Byte/div.bpsc
Debugger.exe -v ../../../Tests/Byte/dstore.bpsc
Debugger.exe -v ../../../Tests/Byte/eq.bpsc
Debugger.exe -v ../../../Tests/Byte/fetch.bpsc
Debugger.exe -v ../../../Tests/Byte/jz.bpsc
Debugger.exe -v ../../../Tests/Byte/local.bpsc
Debugger.exe -v ../../../Tests/Byte/lt.bpsc
Debugger.exe -v ../../../Tests/Byte/narg.bpsc 5
Debugger.exe -v ../../../Tests/Byte/pop.bpsc
Debugger.exe -v ../../../Tests/Byte/push.bpsc
Debugger.exe -v ../../../Tests/Byte/ret.bpsc
Debugger.exe -v ../../../Tests/Byte/sarg.bpsc 'STRING'
Debugger.exe -v ../../../Tests/Byte/store.bpsc
Debugger.exe -v ../../../Tests/Byte/sub.bpsc
Debugger.exe -v ../../../Tests/Byte/band.bpsc
Debugger.exe -v ../../../Tests/Byte/neg.bpsc
Debugger.exe -v ../../../Tests/Byte/shl.bpsc
Debugger.exe -v ../../../Tests/Byte/len.bpsc
Debugger.exe -v ../../../Tests/Byte/darr.bpsc
Debugger.exe -v ../../../Tests/Byte/dcont.bpsc
Debugger.exe -v ../../../Tests/Byte/sfetch.bpsc
Debugger.exe -v ../../../Tests/Byte/sstore.bpsc
Debugger.exe -v ../../../Tests/Byte/ntos.bpsc
Debugger.exe -v ../../../Tests/Byte/ston.bpsc
Debugger.exe -v ../../../Tests/Byte/smatch.bpsc
Debugger.exe -v ../../../Tests/Byte/subs.bpsc
Debugger.exe -n ../../../Tests/Byte/nret.bpsc
Debugger.exe -s ../../../Tests/Byte/sret.bpsc
Debugger.exe -v ../../../Tests/Byte/insert_performance.bpsc
Debugger.exe -v ../../../Tests/Byte/eq_performance.bpsc
Debugger.exe -v ../../../Tests/Byte/match_performance.bpsc